RoRs/LateManagermentServer/config/routes.rb
Rails.application.routes.draw do

  devise_for :users , :controllers => { omniauth_callbacks: 'omniauth_callbacks' }

  root to: 'homes#index'

  resources :users
  resources :messages

  # API routing
  namespace :api, defaults: { format: :json } do
    scope :v1 do
      resources :users
      resources :messages
    end
  end

  get '*path', to: 'api/base#error_404'
end

RoRs/LateManagermentServer/app/models/message.rb
class Message < ActiveRecord::Base
  belongs_to :user
  # For trailing white spaces
  strip_attributes

  # Soft delete with paranoia
  acts_as_paranoid

  validates :description, length: { maximum: 255 }, presence: true

  scope :sorted_by_newest, lambda { order(created_at: :desc) }
  scope :with_time, lambda { |time|
    case time
      when 'Daily'
        where("messages.created_at >= ? AND messages.created_at <= ?", 1.day.ago, Time.now)
      when 'Weekly'
        where("messages.created_at >= ? AND messages.created_at <= ?", 7.day.ago, Time.now)
      when 'Monthly'
        where("messages.created_at >= ? AND messages.created_at <= ?", 30.day.ago, Time.now)
      end
  }

end

RoRs/LateManagermentServer/app/controllers/api/messages_controller.rb
class Api::MessagesController < Api::BaseController
  include MessageConcern

  def index
    @messages = Message.all
  end

  def show
  end

  def create
    created = create_message
    if created
      render action: :show
    else
      error_400
    end
  end

  private
    def set_user(number)
      user = User.where(phone_number: number).first
    end

    def get_phone_number(message)
      split_messages = message.split('-')
      old_phone_number = nil
      if split_messages.count > 1
        old_phone_number = split_messages.first.delete(' ')
        if old_phone_number[0] == '0'
          old_phone_number[0] = '+84'
        end
      end
      old_phone_number
    end

    def create_message
      if validate_params
        user = set_user(params[:phone_number])
        if !user
          old_phone_number = get_phone_number(params[:description])
          if old_phone_number
            user = set_user(old_phone_number)
          end
        end

        @message = Message.new(message_params)
        if !user
          @message.user_id = 1000000001
        else
          @message.user_id = user.id
        end
        @message.save
      else
        false
      end
    end

    def validate_params
      if params[:phone_number].present? && params[:description].present?
        true
      else
        false
      end
    end
end

RoRs/LateManagermentServer/app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  include MessageConcern

  before_action :set_filter, :set_messages_with_pagination, only: [:index]

  def index
    set_flash :info, (I18n.t 'messages.empty') unless @messages.any?
  end

  def show
  end

  def edit
  end

  def new
  end

  def update
  end

  def create
  end

  def destroy
  end

  private
    def set_filter
      @filters = Settings.time.filter
    end
end

RoRs/LateManagermentServer/app/helpers/messages_helper.rb
module MessagesHelper
end

RoRs/LateManagermentServer/app/views/messages/_messages.html.erb
<%- model_class = Message -%>
<%= content_tag :div, :class => "panel-heading" do %>
    <%= page_entries_info @messages %>
<% end %>
    <div class="table-responsive">
        <table class="table table-striped table-hover bg-white">
            <thead>
                <tr>
                    <th class="col-md-2"><%= model_class.human_attribute_name(:user_name) %></th>
                    <th class="col-md-3"><%= model_class.human_attribute_name(:sending_number) %></th>
                    <th class="col-md-3"><%= model_class.human_attribute_name(:message) %></th>
                    <th class="col-md-3"><%= model_class.human_attribute_name(:sending_time) %></th>
                    <th class="col-md-1">Detail</th>
                </tr>
            </thead>
            <tbody>
                <% @messages.each do |message| %>
                <tr>
                    <td><%= message.user.try(:name) %></td>
                    <td><%= message.try(:phone_number) %></td>
                    <td><%= message.description %></td>
                    <td><%= message.created_at %></td>
                    <td>
                        <div class="pull-left">
                            <%= link_to message_path(message), :class => 'btn btn-default' do %>
                                <%= content_tag(:span, nil, class: 'fa fa-list') %>
                            <% end %>
                        </div>
                    </td>
                </tr>
                <% end %>
            </tbody>
        </table>
    </div>
<%= content_tag :div, :class => 'panel-footer text-center' do %>
    <%= paginate @messages %>
<% end %>

RoRs/LateManagermentServer/app/views/messages/_search.html.erb
<form id="messageSearchForm" method="GET" action="<%= search_action %>">
    <div class="col-sm-3">
        <div class="form-group">
            <label><em class="fa fa-search"></em>&nbsp;<%= t("messages.search.name_phone") %></label>
            <%= text_field_tag :name_phone, params[:name_phone], placeholder: t("messages.search.placeholder"), class: "form-control", style: "border-radius: 3px" %>
        </div>
    </div>
    <div class="col-sm-3">
        <div class="form-group">
            <label><em class="fa fa-search"></em>&nbsp;<%= t("messages.search.time") %></label>
            <%= select_tag "time", options_for_select(@filters, selected: params[:time]), prompt: "---", class: "form-control" %>
        </div>
    </div>
    <div class="col-sm-2">
        <div class="form-group">
            <label><em></em>&nbsp;</label>
            <div><%= submit_tag "Submit", value: t("messages.search.search"), name: nil, class: "btn btn-primary" %></div>
        </div>
    </div>
</form>

RoRs/LateManagermentServer/app/views/messages/edit.html.erb
<h1>Messages#edit</h1>
<p>Find me in app/views/messages/edit.html.erb</p>

RoRs/LateManagermentServer/app/views/messages/index.html.erb
<div class='col-lg-12'>
    <div class="panel panel-default" style="margin-bottom: 40px;">
        <div class="panel-body">
            <%= render partial: '/messages/search', locals: { search_action: messages_path } %>
        </div>
    </div>
</div>

<div class="col-lg-12">
    <% if @messages.present? %>
        <div class="panel panel-default" id="messages">
            <%= render partial: 'messages', locals: { messages: @messages }%>
        </div>
    <% end %>
</div>

RoRs/LateManagermentServer/app/views/messages/new.html.erb
<h1>Messages#new</h1>
<p>Find me in app/views/messages/new.html.erb</p>

RoRs/LateManagermentServer/app/views/messages/show.html.erb
<div class="col-lg-12">
    <div class="panel panel-default">
        <%= content_tag :div, :class => "panel-body" do %>
            <%- model_class = Message -%>
            <dl class="dl-horizontal">
                <dt><strong><%= model_class.human_attribute_name(:user_name) %>:</strong></dt>
                <dd><%= @message.user.try(:name) %></dd>

                <dt><strong><%= model_class.human_attribute_name(:sending_number) %>:</strong></dt>
                <dd><%= @message.try(:phone_number) %></dd>

                <dt><strong><%= model_class.human_attribute_name(:message) %>:</strong></dt>
                <dd><%= @message.description %></dd>
                <dt><strong><%= model_class.human_attribute_name(:sending_time) %>:</strong></dt>
                <dd><%= @message.created_at %></dd>
            </dl>
            <div class="pull-left">
                <%= link_to t("helpers.links.back"),
                                messages_path, :class => 'btn btn-default'  %>
            </div>
        <% end %>
    </div>
</div>