RoRs/LateManagermentServer/config/routes.rb
Rails.application.routes.draw do

  devise_for :users , :controllers => { omniauth_callbacks: 'omniauth_callbacks' }

  root to: 'homes#index'

  resources :users
  resources :messages

  # API routing
  namespace :api, defaults: { format: :json } do
    scope :v1 do
      resources :users
      resources :messages
    end
  end

  get '*path', to: 'api/base#error_404'
end

RoRs/LateManagermentServer/app/views/layouts/_confirm_dialog.html.erb
<div class="modal fade" id="confirmModal" role="dialog">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <h4 class="modal-title"><%= t("helpers.confirm_title") %></h4>
            </div>
            <div class="modal-body">
                <p></p>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-primary yes" data-dismiss="modal">Yes</button>
                <button type="button" class="btn btn-default" data-dismiss="modal">No</button>
            </div>
        </div>
    </div>
</div>

RoRs/LateManagermentServer/app/views/layouts/_footer.html.erb
<footer class="serverad-footer">
    <div class="serverad-copyright">
        <p>Copyright &copy; 2016 DMM.COM Labo</p>
    </div>
</footer>

RoRs/LateManagermentServer/app/views/layouts/_header.html.erb
<div class="navbar navbar-inverse" role="navigation">
    <div class="navbar-header">
        <div class="logo">
            <h1 class="brand-logo">Late Managerment</h1>
            <h1 class="single-logo">
            </h1>
        </div>
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
          <span class="sr-only">Lat</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
    </div>
    <%= render 'layouts/sidebar' %>
</div>

<div class="navbar navbar-inverse" role="navigation">
    <div class="navbar-header">
        <div class="logo">
            <h1 class="brand-logo">Late Managerment</h1>
            <h1 class="single-logo"></h1>
        </div>
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
    </div>
    <ul class="nav nav-wrapper navbar-right">
        <li>
            <% if current_user -%>
                <%= link_to '', destroy_user_session_path, class: "fa fa-sign-out", :method => :delete %>
            <% else %>
                <%= link_to '', user_google_oauth2_omniauth_authorize_path, class: "fa fa-sign-in" %>
            <% end %>
        </li>
    </ul>
</div>

RoRs/LateManagermentServer/app/views/layouts/_message.html.erb
<% if !flash.empty? %>
    <% flash.each do |name, msg| %>
        <% if msg.is_a?(String) %>
            <%= content_tag :div, :class => "alert alert-#{name}", :role => "alert" do %>
                <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <%= msg %>
            <% end %>
        <% end %>
    <% end %>
    <% flash.clear %>
<% end %>

RoRs/LateManagermentServer/app/views/layouts/_page_title.html.erb
<div class="page-header">
    <h3><%= page_title %></h3>
    <small><%= page_sub_title %></small>
</div>

RoRs/LateManagermentServer/app/views/layouts/_sidebar.html.erb
<div class="navbar-default sidebar" role="navigation">
    <div class="navbar-collapse collapse serverad-sidebar">
        <%= make_side_bar do %>
            <li class="sidebar-group"><span><%= t('layout.sumary') %></span></li>
            <%= make_side_bar_link t('layout.late_report'), messages_path, 'fa fa-archive', true %>
            <% if admin_permit? %>
                <%= make_side_bar_link t('layout.users'), users_path, 'fa fa-users', true %>
            <% end %>
        <% end %>
    </div>
</div>

RoRs/LateManagermentServer/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
    <title>Late Managerment</title>
    <%= stylesheet_link_tag "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <meta name="keywords" content="">
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width">
    <%= csrf_meta_tags %>
</head>
<body>
    <section id="container">
        <%= render 'layouts/header' %>
        <%= render 'layouts/sidebar' %>
        <div class="serverad-content-wrapper">
            <div class="serverad-content">
                <%= render 'layouts/page_title' %>
                <%= render 'layouts/message' %>
                <%= yield %>
            </div>
        </div>
        <%= render 'layouts/footer' %>
        <%= render 'layouts/confirm_dialog' %>
    </section>
</body>
</html>